// <auto-generated />
using System;
using Dhadgar.Nodes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhadgar.Nodes.Data.Migrations
{
    [DbContext(typeof(NodesDbContext))]
    [Migration("20260123072445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.AgentCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NotAfter")
                        .HasDatabaseName("ix_agent_certificates_expiry");

                    b.HasIndex("Thumbprint")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_certificates_thumbprint");

                    b.HasIndex("NodeId", "IsRevoked")
                        .HasDatabaseName("ix_agent_certificates_node_active");

                    b.ToTable("agent_certificates", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.EnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsedByNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_enrollment_tokens_expires");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollment_tokens_hash");

                    b.HasIndex("OrganizationId", "ExpiresAt")
                        .HasDatabaseName("ix_enrollment_tokens_org_expires");

                    b.ToTable("enrollment_tokens", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_nodes_active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("LastHeartbeat")
                        .HasDatabaseName("ix_nodes_last_heartbeat");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_nodes_org_name_unique")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_nodes_org_status");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.NodeCapacity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AvailableDiskBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("AvailableMemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentGameServers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxGameServers")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_node_capacities_node_id");

                    b.HasIndex("MaxGameServers", "CurrentGameServers")
                        .HasDatabaseName("ix_node_capacities_availability");

                    b.ToTable("node_capacities", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.NodeHardwareInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<long>("DiskBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("MemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("NetworkInterfaces")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_node_hardware_inventories_node_id");

                    b.ToTable("node_hardware_inventories", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.NodeHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveGameServers")
                        .HasColumnType("integer");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<string>("HealthIssues")
                        .HasColumnType("jsonb");

                    b.Property<double>("MemoryUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_node_healths_node_id");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("ix_node_healths_reported_at");

                    b.ToTable("node_healths", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.AgentCertificate", b =>
                {
                    b.HasOne("Dhadgar.Nodes.Data.Entities.Node", "Node")
                        .WithMany("Certificates")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.NodeCapacity", b =>
                {
                    b.HasOne("Dhadgar.Nodes.Data.Entities.Node", "Node")
                        .WithOne("Capacity")
                        .HasForeignKey("Dhadgar.Nodes.Data.Entities.NodeCapacity", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.NodeHardwareInventory", b =>
                {
                    b.HasOne("Dhadgar.Nodes.Data.Entities.Node", "Node")
                        .WithOne("HardwareInventory")
                        .HasForeignKey("Dhadgar.Nodes.Data.Entities.NodeHardwareInventory", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.NodeHealth", b =>
                {
                    b.HasOne("Dhadgar.Nodes.Data.Entities.Node", "Node")
                        .WithOne("Health")
                        .HasForeignKey("Dhadgar.Nodes.Data.Entities.NodeHealth", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Dhadgar.Nodes.Data.Entities.Node", b =>
                {
                    b.Navigation("Capacity");

                    b.Navigation("Certificates");

                    b.Navigation("HardwareInventory");

                    b.Navigation("Health");
                });
#pragma warning restore 612, 618
        }
    }
}
