// <auto-generated />
using System;
using System.Collections.Generic;
using Dhadgar.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhadgar.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.ClaimDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemClaim")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_claim_definitions_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_claim_definitions_name");

                    b.ToTable("claim_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Category = "organization",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View organization details",
                            IsSystemClaim = true,
                            Name = "org:read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Category = "organization",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update organization settings",
                            IsSystemClaim = true,
                            Name = "org:write"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Category = "organization",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete organization",
                            IsSystemClaim = true,
                            Name = "org:delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Category = "organization",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage billing and subscriptions",
                            IsSystemClaim = true,
                            Name = "org:billing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Category = "members",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View organization members",
                            IsSystemClaim = true,
                            Name = "members:read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Category = "members",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Invite new members",
                            IsSystemClaim = true,
                            Name = "members:invite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Category = "members",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Remove members",
                            IsSystemClaim = true,
                            Name = "members:remove"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Category = "members",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assign member roles",
                            IsSystemClaim = true,
                            Name = "members:roles"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Category = "servers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View servers",
                            IsSystemClaim = true,
                            Name = "servers:read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Category = "servers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create and update servers",
                            IsSystemClaim = true,
                            Name = "servers:write"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Category = "servers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete servers",
                            IsSystemClaim = true,
                            Name = "servers:delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Category = "servers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Start servers",
                            IsSystemClaim = true,
                            Name = "servers:start"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Category = "servers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stop servers",
                            IsSystemClaim = true,
                            Name = "servers:stop"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Category = "servers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Restart servers",
                            IsSystemClaim = true,
                            Name = "servers:restart"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Category = "nodes",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View nodes",
                            IsSystemClaim = true,
                            Name = "nodes:read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Category = "nodes",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage node configuration",
                            IsSystemClaim = true,
                            Name = "nodes:manage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            Category = "files",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View and download files",
                            IsSystemClaim = true,
                            Name = "files:read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            Category = "files",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upload and modify files",
                            IsSystemClaim = true,
                            Name = "files:write"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            Category = "files",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete files",
                            IsSystemClaim = true,
                            Name = "files:delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000001"),
                            Category = "mods",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View mods",
                            IsSystemClaim = true,
                            Name = "mods:read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000002"),
                            Category = "mods",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Install and update mods",
                            IsSystemClaim = true,
                            Name = "mods:write"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000003"),
                            Category = "mods",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uninstall mods",
                            IsSystemClaim = true,
                            Name = "mods:delete"
                        });
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.LinkedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_linked_accounts_user_id");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_linked_accounts_provider_account");

                    b.ToTable("linked_accounts", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_organizations_active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_organizations_owner_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_active")
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalAuthId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HasPasskeysRegistered")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPasskeyAuthAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreferredOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_users_active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ExternalAuthId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_auth_id");

                    b.HasIndex("PreferredOrganizationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.UserOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InvitationAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("viewer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_user_organizations_organization_id");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_organizations_active_membership")
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.ToTable("user_organizations", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.UserOrganizationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClaimType")
                        .HasColumnType("integer");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserOrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserOrganizationId")
                        .HasDatabaseName("ix_user_org_claims_user_org_id");

                    b.HasIndex("UserOrganizationId", "ClaimValue")
                        .HasDatabaseName("ix_user_org_claims_lookup");

                    b.ToTable("user_organization_claims", (string)null);
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.LinkedAccount", b =>
                {
                    b.HasOne("Dhadgar.Identity.Data.Entities.User", "User")
                        .WithMany("LinkedAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Dhadgar.Identity.Data.Entities.LinkedAccountMetadata", "ProviderMetadata", b1 =>
                        {
                            b1.Property<Guid>("LinkedAccountId");

                            b1.Property<string>("AvatarUrl");

                            b1.Property<string>("DisplayName");

                            b1.Property<Dictionary<string, string>>("ExtraData")
                                .IsRequired();

                            b1.Property<string>("Username");

                            b1.HasKey("LinkedAccountId");

                            b1.ToTable("linked_accounts");

                            b1.ToJson("ProviderMetadata");

                            b1.WithOwner()
                                .HasForeignKey("LinkedAccountId");
                        });

                    b.Navigation("ProviderMetadata");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.Organization", b =>
                {
                    b.HasOne("Dhadgar.Identity.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Dhadgar.Identity.Data.Entities.OrganizationSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId");

                            b1.Property<bool>("AllowMemberInvites");

                            b1.Property<Dictionary<string, string>>("CustomSettings")
                                .IsRequired();

                            b1.Property<int>("MaxMembers");

                            b1.Property<bool>("RequireEmailVerification");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations");

                            b1.ToJson("Settings");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("Dhadgar.Identity.Data.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhadgar.Identity.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.User", b =>
                {
                    b.HasOne("Dhadgar.Identity.Data.Entities.Organization", "PreferredOrganization")
                        .WithMany()
                        .HasForeignKey("PreferredOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreferredOrganization");
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.UserOrganization", b =>
                {
                    b.HasOne("Dhadgar.Identity.Data.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dhadgar.Identity.Data.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dhadgar.Identity.Data.Entities.User", "User")
                        .WithMany("Organizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedBy");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.UserOrganizationClaim", b =>
                {
                    b.HasOne("Dhadgar.Identity.Data.Entities.User", "GrantedBy")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhadgar.Identity.Data.Entities.UserOrganization", "UserOrganization")
                        .WithMany("CustomClaims")
                        .HasForeignKey("UserOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantedBy");

                    b.Navigation("UserOrganization");
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.Organization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.User", b =>
                {
                    b.Navigation("LinkedAccounts");

                    b.Navigation("Organizations");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Dhadgar.Identity.Data.Entities.UserOrganization", b =>
                {
                    b.Navigation("CustomClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
