using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace Dhadgar.Identity.Authentication;

public static class AuthSchemes
{
    /// <summary>
    /// External cookie scheme for OAuth provider callbacks.
    /// </summary>
    public const string External = "External";

    /// <summary>
    /// JWT Bearer scheme for API authentication.
    /// Validates tokens generated by JwtService (/exchange endpoint).
    /// </summary>
    public const string Bearer = JwtBearerDefaults.AuthenticationScheme;
}
